package com.enterpriseai.ticketcopilot.model;

public enum AbstentionReasonCode {
    NONE,
    NO_RETRIEVAL_EVIDENCE,
    MISSING_REQUIRED_INFORMATION,
    INVALID_STRUCTURED_OUTPUT,
    MISSING_CITATION,
    INVALID_CITATION,
    PROVIDER_FAILURE,
    UNSUPPORTED_PROVIDER,
    UNSUPPORTED_PROTOCOL,
    OUTPUT_POLICY_REJECTED
}
